services:
  postgres:
    image: postgres:15
    container_name: user_mgmt_postgres
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_user_mgmt:/var/lib/postgresql/data

volumes:
  pgdata_user_mgmt:
